### ISSUE TITLE
About the javascript plugin.

### ISSUE THREAD

**Issue by jcdesimp** [layeh/piepan#15]
Where can I find some more details on what functionality is available via the javascript scripting interface for Piepan. Not so much the mumble functionality but the overall javascript functionality. For example it looks as if it has _.js template functionality based on one of the examples. Does it have any other js libraries or helper functions built in? 

Also what is the scope of things when the scripts are run under the hood? Are scripts run every time an event is triggered? Are global variable persistent across these events? Is there any way of persisting data throughout various events for things such as spam prevention?

Any other neat details you could provide would be much appreciated, really love how far it's come.

**Comment by bontibon** [comment]
> Where can I find some more details on what functionality is available via the javascript scripting interface for Piepan. Not so much the mumble functionality but the overall javascript functionality.

The plugin uses the [otto JavaScript library](https://github.com/robertkrimen/otto). I believe it conforms to the ECMA-262 spec.

>  For example it looks as if it has _.js template functionality based on one of the examples. Does it have any other js libraries or helper functions built in?

[underscore.js](http://underscorejs.org/) is currently the only helper library that is included.

> Also what is the scope of things when the scripts are run under the hood? 

Every `javascript` block is executed in its own scope.

> Are scripts run every time an event is triggered?

Script **files** are executed once when piepan starts. Registered event listener functions in the scripts are executed when the particular event is triggered.

> Are global variable persistent across these events? 

Yes, the JavaScript interpreters are only destroyed when the program exits.

> Is there any way of persisting data throughout various events for things such as spam prevention?

Right now, you would have to use an external program (using `piepan.Process.New`) to read/write external data. This is not ideal, and I hope to have a better solution implemented for 0.5.0.

**Comment by jcdesimp** [comment]
Thanks for the replies. Im looking for a way to write to files, I'm able to "read" via a system call to cat but can't seem to find a way to write, do you know of any?

**Comment by bontibon** [comment]
I have just added 2d0f6e4ccd84135c91e88b12aebefd3fe2a78dbb. Let me know if it helps you out any.

**Comment by jcdesimp** [comment]
seems useful, thanks.
