### ISSUE TITLE
Unable to build since Lua added

### ISSUE THREAD

**Issue by jcdesimp** [layeh/piepan#16]
I get errors when trying to build piepan now that the lua stuff is there:
````
# github.com/aarzilli/golua/lua
ld: library not found for -llua
clang: error: linker command failed with exit code 1 (use -v to see invocation)
````

I have no interest in using the Lua component so is there a way I can just exclude it so that builds continue going smoothly?

**Comment by bontibon** [comment]
1. Make sure that Lua 5.1 development libraries are installed, or
2. If you would like to disable Lua support, comment out/remove the following line from `cmd/piepan/main.go`:

                _ "github.com/layeh/piepan/plugins/lua"

**Comment by jcdesimp** [comment]
I don't see any instructions in the readme for installing Lua. will touching the main source file affect updating in the future?

**Comment by bontibon** [comment]
The readme will  be updated when v0.5.0 is released.

I have just made a change (5167d8e04677f8cdcd78769470126e85f606442b) that allows you to build piepan with specific plugins.  Running the following will build the piepan executable with only JavaScript support:

    go build -o piepan $GOPATH/src/github.com/layeh/piepan/cmd/piepan/{javascript.go,main.go}

**Comment by jcdesimp** [comment]
@bontibon So does that go after the "go get..." command then?

**Comment by bontibon** [comment]
The piepan source code _should_ be downloaded into your $GOPATH, but just in case it isn't, you can run:

    go get -u github.com/layeh/piepan/{plugins/javascript,}

Then you can run my previous command.

**Comment by jcdesimp** [comment]
@bontibon doesn't the "go get.." command build it automatically?

**Comment by bontibon** [comment]
I have updated the Ubuntu build instructions. Let me know if they work for you.

**Comment by jcdesimp** [comment]
@bontibon 
I get the following error when trying to actually build it:
```
# command-line-arguments
cannot create piepan: Is a directory
```

**Comment by bontibon** [comment]
There must be a directory named `piepan` where you currently are.  You can try switching to another directory, or changing the output name: `-o <another name here>`.

**Comment by jcdesimp** [comment]
@bontibon there us a directory names piepan where I am, I run this from an update script to update piepan and copy it to my project where I'm building my bot. This is separate form the $GOPATH tho so shouldn't everything be happening in the GOPATH? I'm not too familiar with GO development so I'm a little unsure how this all works.

**Comment by bontibon** [comment]
Due to how the new plugin-based system works, generated binaries will not be installed to `$GOPATH/bin`.  You can modify your script to reflect these changes:

    #!/bin/bash

    if [ "$1" ]
    then
        export GOPATH=$1;
        go get -u github.com/layeh/piepan
        go get -u github.com/layeh/piepan/plugins/javascript

        go build -o ./piepan/piepan $GOPATH/src/github.com/layeh/piepan/cmd/piepan/{javascript,main}.go
    else
        echo "No gopath given!";
    fi

**Comment by jcdesimp** [comment]
@bontibon So this will build it and place the resulting binary in the ```./piepan/piepan``` directory?

**Comment by bontibon** [comment]
That is correct.

**Comment by jcdesimp** [comment]
Awesome, thank you. Will try it out and report back.

**Comment by jcdesimp** [comment]
Seems to work, thank!
