### ISSUE TITLE
Reference library/docs for javascript

### ISSUE THREAD

**Issue by jcdesimp** [layeh/piepan#18]
I was wondering if there is a file somewhere that documents the various functions and fields for the piepan javascript interface. I mainly want this for linking with an IDE to enable code completion, documentation, and to satisfy those annoying warnings about the piepan objects mot being known. Just a simple request if such a file already exists. Thanks.

**Comment by bontibon** [comment]
I'm not sure what kind of file you were looking for, but I'm pretty sure it does not exist.

If you were to make such a document yourself, the two sources you would use would be:
- the [gumble API](https://godoc.org/github.com/layeh/gumble/gumble), and
- the [piepan JavaScript plugin API](https://github.com/layeh/piepan/blob/master/plugins/javascript/README.md)

**Comment by jcdesimp** [comment]
ok thanks
