### ISSUE TITLE
Sound transmissions incredibly choppy recently.

### ISSUE THREAD

**Issue by jcdesimp** [layeh/piepan#20]
The sounds played via piepan would always have occasional lag issues. But recently the sounds have been pretty much always choppy/laggy. Not sure if its an issue with PiePan or my system configuration but I know previously it was much better than it is now.

**Comment by matthieugrieger** [comment]
I don't directly use piepan, but I do use gumble for my mumbledj project. I believe most (if not all) of piepan's backend is based on gumble, and I haven't experienced any audio issues lately.

From my experience the choppiness/lag comes from not having enough resources to deal with the transcoding of audio. It is fairly resource intensive.

**Comment by bontibon** [comment]
The two resources that I would first investigate are CPU (as @matthieugrieger mentioned) and bandwidth: piepan re-encodes media on the fly to match the Mumble format, and then it needs to send that audio stream to the server. Right now, gumble (the Mumble library that piepan uses), does not use UDP for sending audio packets; something that the official Mumble client does. Once I have that implemented, you *may* see audio becoming less choppy for you, but it's not guaranteed.

**Comment by jcdesimp** [comment]
@bontibon Ok cool, it's not a devastating thing but I'll test it out once the UDP transmissions are implemented.

**Comment by Zero3** [comment]
Just adding an anecdotal comment here: I had some audio choppyness with the pre-Go version of Piepan, but since upgrading recently I've had no noticable choppyness. It could be unrelated to the Piepan upgrade, but so far so good here. I run the bot on the same server as the Mumble server.

**Comment by bontibon** [comment]
The outgoing audio system in [gumble](https://github.com/layeh/gumble) has recently had its code rewritten.

Please open another issue if you experience choppiness again after building piepan using the gumble's master branch.
