### ISSUE TITLE
Access tokens

### ISSUE THREAD

**Issue by Doidel** [layeh/piepan#26]
Hello

I am using the javascript plugin of piepan. I see that gumble supports AccessTokens, however I am having troubles finding a way to use clients with my mumble bot.
Could you give me a hint on how to tackle this?

Thanks and king regards
Doidel

**Comment by Doidel** [comment]
I seed that in main.go you can pass username, password and server. I could hardcode access tokens there and compile it, but having a possibility to define the token at script startup too would be nice...

**Comment by bontibon** [comment]
The `access-token` flag has been added in aefa379d71a8903aa1520ad77583d1281765c48b.

**Comment by Doidel** [comment]
Wow thanks man! Awesome!
