### ISSUE TITLE
Sender of a TextMessageEvent is not nil but cannot be dereferenced

### ISSUE THREAD

**Issue by Zero3** [layeh/piepan#29]
I have an `piepan.On("message", ...)` binding (in a Go Lua script) that catches messages sent to my piepan bot. It sometimes receives message through the Mumble ICE interface which causes a problem: I use `msgEvent.Sender` in my script, but it is not `nil` when the message is from ICE as it used to be in previous versions of piepan. But when I try to look at the fields of `Sender`, the script terminates with the cryptic error `cannot index non-struct pointer`.

This seems like a bug, but maybe something changed and this is how it is supposed to be now. How should one check whether the sender is valid user now?

**Comment by bontibon** [comment]
This was a bug in [gopher-lua](https://github.com/layeh/gopher-luar) that [has now been fixed](https://github.com/layeh/gopher-luar/commit/3ce14798816d97ed17bb956c365b26dbaed3df92). Updating gopher-lua using the command below then rebuilding piepan should solve your issue:

```shell
go get -u github.com/layeh/gopher-luar
```

Thank you for reporting this!

**Comment by Zero3** [comment]
Sounds good :). Glad to be able to help. Thanks for the quick fix - it seems to work here.
