### ISSUE TITLE
User#Move requires 1 argument in documentation but 2 are expected at runtime

### ISSUE THREAD

**Issue by Zero3** [layeh/piepan#30]
When i try to run `piepan.Self.Move(msgEvent.Sender.Channel)` in response to a `TextMessageEvent` in a Go Lua script, the script crashes with `invalid number of function argument (2 expected, got 1)`. The [docs](https://godoc.org/github.com/layeh/gumble/gumble#User.Move) only appears to state a single argument though, the channel to move to.

Is this a bug, or am I missing something about a second argument somewhere?

**Comment by bontibon** [comment]
`Move` is a method of `User`, therefore, you need to pass the User as the first argument. This can be done using either of the ways below (the former being the preferred way):

```lua
piepan.Self:Move(msgEvent.Sender.Channel)
```

```lua
piepan.Self.Move(piepan.Self, msgEvent.Sender.Channel)
```

**Comment by Zero3** [comment]
Ah, this is new. Thanks! It works now.
