### ISSUE TITLE
Non-latin characters no longer work in regular expressions

### ISSUE THREAD

**Issue by Zero3** [layeh/piepan#31]
In previous versions of Piepan I used `string.match()` with a regular expression to sanitize user input. With the latest version, using Go Lua, this no longer works with non-latin characters such as the Danish `æ`, `ø` and `å`.

A trivial example:

    print(string.match("abc", "abc"))
    abc

    print(string.match("æøå", "æøå"))
    nil

Do I need to do something special to be able to use these non-latin characters again?

**Comment by bontibon** [comment]
This is an issue with [gopher-lua](https://github.com/yuin/gopher-lua), the Lua implementation that piepan uses. You should open a [new issue](https://github.com/yuin/gopher-lua/issues/new) on its project page.
