### ISSUE TITLE
wtf

### ISSUE THREAD

**Issue by marienuac** [layeh/piepan#33]
https://github.com/layeh/piepan/blob/master/plugins/golua/connection.go

func (p *Plugin) OnConnect(e *gumble.ConnectEvent) {
	pp := p.state.GetGlobal("piepan").(*lua.LTable)
	pp.RawSetH(lua.LString("Self"), luar.New(p.state, e.Client.Self))
>>>	pp.RawSetH(lua.LString("Users"), luar.New(p.state, e.Client.Users))
>>>	pp.RawSetH(lua.LString("Users"), luar.New(p.state, e.Client.Channels))

why?

**Comment by bontibon** [comment]
Fixed in 93f256fe27e683dc92327aedbdd9549479493fee. Thank you for the report!

**Comment by marienuac** [comment]
awesome! :D
