### ISSUE TITLE
Any plans to bring Javascript back?

### ISSUE THREAD

**Issue by jcdesimp** [layeh/piepan#34]
I had a pretty decently sized code base of Javascript I was using with Piepan, all useless now. It wouldn't really be worth reimplementing them all in Lua at this point.

**Comment by bontibon** [comment]
> Any plans to bring Javascript back?

Unfortunately, no. It's too much of a pain to maintain support for multiple scripting languages, and it increases complexity when adding new features.

If you want to continue using JavaScript for your Mumble bot, you could try [node-mumble](https://github.com/Rantanen/node-mumble).

**Comment by mathom** [comment]
@jcdesimp if you're interested in maintaining/backporting features from piepan into an earlier fork, I'm planning on using https://github.com/mathom/piepan for my own project since I have a lot of JS code as well. I still need to look into node-mumble but for now I'll just be using the fork.
