### ISSUE TITLE
Timer help

### ISSUE THREAD

**Issue by Hardcor3UK** [layeh/piepan#35]
I can't get the piepan Timer to work at all, I had it working fine in javascript version of plugin and my lua plugin for the old C version of piepan but since 0.8 I can not get the timer working at all, don't know if its broken or if im doing something totally wrong.

Quick example of something i tried to test it out.

```
local timer = nil

function timerTest()
	print("callback: " .. os.time())
end

piepan.On('connect', function()
	print("Before: " .. os.time())
	timer = piepan.Timer.New(timerTest(), 5000)
	print("after: " .. os.time())
end)
```

I just get `attempt to call a non-function object` error on the line of Timer.New all the time.
Also the timer fires the function instantly, instead of after the time has passed, along with the error.
`print("after: " .. os.time())` is never executed due to the script halting on error i guess.

I have a feeling this is just me totally messing it up, so some help would be appreciated, thanks.

**Comment by Ivan-Roger** [comment]
I suppose it comes from you :
`piepan.Timer.New(timerTest(), 5000)`
for me it would be the fact that it did put a function call instead of the function name !
try `piepan.Timer.New(timerTest, 5000)`

**Comment by Hardcor3UK** [comment]
I tried it with a function name also before (and just tried it now to make sure i wasn't imagining i did) and it just gives the `attempt to call a non-function object` error and timer never executes the function.

**Comment by Ivan-Roger** [comment]
I'm new to Lua so i can't help.

**Comment by bontibon** [comment]
There was bug that has now been fixed. The working code should look as follows:
```lua
local timer = nil

function timerTest()
    print("callback: " .. os.time())
end

piepan.On('connect', function()
    print("Before: " .. os.time())
    timer = piepan.Timer.New(timerTest, 5000)
    print("after: " .. os.time())
end)
```

**Comment by Hardcor3UK** [comment]
Thanks for the quick fix :)
