### ISSUE TITLE
Users.Find

### ISSUE THREAD

**Issue by JkkaMr** [layeh/piepan#38]
Everytime I'm trying to use function Users.Find I get error `reflect.Value.Convert: value of type string cannot be converted to type uint32`.

My code is:
`local user = piepan.Users:Find("username")`

Am I doing something wrong?

**Comment by bontibon** [comment]
There was a bug in gopher-luar, a library that piepan uses. I have just pushed a fix (https://github.com/layeh/gopher-luar/commit/ab3f305945becf90dbde5962755dc044cb78acee).

Updating gopher-luar (`go get -u layeh.com/gopher-luar`) and rebuilding piepan should fix the issue.

**Comment by JkkaMr** [comment]
Thank you very much for a quick fix, working like a charm!
